language: python
python:
- '2.7'
sudo: required
services:
- docker
before_install:
- sudo apt-get update
- sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-engine
- sudo pip install -U docker-compose
- sudo pip install --upgrade ndg-httpsclient
- docker-compose -f docker/ci.docker-compose.yml pull
- docker-compose -f docker/ci.docker-compose.yml up -d
- sleep 30
- docker exec docker_sfmweiboharvester_1 python -m unittest discover
install: pip install -r requirements/master.txt
script: python -m unittest discover
notifications:
  email:
  - ychtan@email.gwu.edu
  slack:
    secure: WvW6PngH7aUrhJh+JvsCJCSPVEDl075qB1TpcyStZjhUIlNP4yBUNlMi+7/JPpTd1E7Ozw4++gzhopB5tn5wJgl2JPlnsTelj++vD1cpK4xTxkkuG6MRWD3Oj1S7J7CCi3QJOil2RMsmd8N3KAZNlmX2xNRvO7e4L07Nj5k37Fy/1kZaoOmNqkNdxl6w4tPBjkn0QuCb/SA5bNO3ss8YyhHgcNUC9oIPSvp2jELcxIE0v1p63RNKkfeP8Itdjp2IgzQTF/hiSYU1l/Q0noHXLAjlICQdlvx6MNGt8gikHlHE8pTsctx2V7VkYKYXg5dEdsUNxitf8PyAHZgYGNOHwfxFttQZpwy4Eewu5uxrxmFh5DxhMBLGFk1mp1xv02JRrBzA3dTThYRpnTRX62tLCFqPJ9T/NylElBP+kaF5qPXsRiIj+TV+db4dO8ZV/YByRRpy3CvNcs+R+EUqpttASpEQN1W/6gWBTofYCYxUrqpjEXv0+tgIh3vmm57+gzwcDrnkxjbEk/TKbeZ5M6jcu1Ps+QBZRFoP5NEeowYfErd7JTwu2RKNRiPbRRjWEIrHTYpOl4vODLFzWiwwVwyt4Yffs42nKl959mqTYK62asGm+ZpKINg8qlltusmReKr54Vq6LISAYLWzQo48CpiinIQLNS4/+jX8wH7IbMqASdc=
