FROM gwul/sfm-base@sha256:07b3495d4496d603d464b3f829f92e61c6d27da8b773e1076e1b6ffcfd643eaf
MAINTAINER Vict Tan <ychtan@email.gwu.edu>

ADD . /opt/sfm-weibo-harvester/
WORKDIR /opt/sfm-weibo-harvester
RUN pip install -r requirements/common.txt -r requirements/release.txt

CMD sh /opt/sfm-setup/setup_reqs.sh \
    && appdeps.py --wait-secs 60 --port-wait mq:5672 --port-wait api:8080 --file-wait /sfm-data/collection_set --file-wait /sfm-data/containers --file-wait /sfm-data/export \
    && gosu sfm python weibo_exporter.py --debug=$DEBUG service mq $RABBITMQ_USER $RABBITMQ_PASSWORD http://api:8080 /sfm-data/containers/$HOSTNAME
