sfmrabbit:
    image: rabbitmq@sha256:397382d2b222f3a298a6c74e93f348fb16f9a7fde2c02ba14122624d852daae3
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmweiboharvester:
    image: gwul/sfm-weibo-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-weibo-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
        - "../../warcprox:/opt/warcprox"
    environment:
        - DEBUG=True
#    restart: always