sfmrabbit:
    image: rabbitmq:3-management
    ports:
        - "15672:15672"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER=sfm_user
        - RABBITMQ_DEFAULT_PASS=password
sfmweiboharvester:
    image: victtan/sfm-weibo-harvester:dev
    links:
        - sfmrabbit:mq
    volumes:
        - "..:/opt/sfm-weibo-harvester"
        - "../../sfm-utils:/opt/sfm-utils"
#    restart: always